EmployeePortal/Areas/Procurement/Models/PurchaseOrder/PurchaseOrderHeaderModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EmployeePortal.Areas.Procurement.Models.PurchaseOrder
{
    public class PurchaseOrderHeaderModel
    {
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string DepartementCode { get; set; }
        public string DepartementName { get; set; }
        public string Npwp { get; set; }
        public string NpwpAddress { get; set; }
        public string VendorCompanyName { get; set; }
        public string VendorCompanyAddress { get; set; }
        public string VendorPhone { get; set; }
        public string VendorCity { get; set; }
        public string VendorRegion { get; set; }
        public string VendorpostalCode { get; set; }
        public string PONumber { get; set; }
        public DateTime CreatedDate { get; set; }
        public string PODate { get; set; }
        public string PaymentStatus { get; set; }
        public string POStatus { get; set; }

        public decimal GrandTotal { get; set; }
        public decimal Ppn { get; set; }
        public decimal GrandTotalAfterTax { get; set; }

        public string StringGrandTotal { get; set; }
        public string stringPpn { get; set; }
        public string StringGrandTotalAfterTax { get; set; }

        public List<PurchaseOrderItemModel> ListItem { get; set; }
        public List<PurchaseOrderVendorCategoryItemModel> ListVendor { get; set; }
    }
}

EmployeePortal/Areas/Procurement/Models/PurchaseOrder/PurchaseOrderItemModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EmployeePortal.Areas.Procurement.Models.PurchaseOrder
{
    public class PurchaseOrderItemModel
    {
        public string VendorName { get; set; }
        public string Specification { get; set; }
        public string PurposeDesc { get; set; }
        public decimal Qty { get; set; }
        public string Uom { get; set; }
        public int? CurrencyId { get; set; }
        public string Currency { get; set; }
        public int PPN { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal TotalPrice { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public string ModifyBy { get; set; }
        public DateTime ModifyDate { get; set; }
        public string PRStatus { get; set; }
        public string BudgetStatus { get; set; }
        public int? MasterPurchaseRequisitionId { get; set; }
        public string PRNumber { get; set; }
        public int? MasterItemId { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string UnitPriceString { get; set; }
        public string TotalPriceString { get; set; }
    }
}

EmployeePortal/Areas/Procurement/Models/PurchaseOrder/PurchaseOrderVendorCategoryItemModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace EmployeePortal.Areas.Procurement.Models.PurchaseOrder
{
    public class PurchaseOrderVendorCategoryItemModel 
    {
        public string VendorId { get; set; }
        public string VendorName { get; set; }
        public decimal Ppn{ get; set; }
        public decimal PpnPrice { get; set; }
        public decimal TotalPrice { get; set; }
        public decimal TotalPriceAfterTax { get; set; }
    }
}

EmployeePortal/Areas/Procurement/Controllers/PurchaseOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EmployeePortal.Areas.Procurement.Models.PurchaseOrder;
using EmployeePortal.Controllers;
using EmployeePortal.Service;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;

namespace EmployeePortal.Areas.Procurement.Controllers
{
    [NoDirectAccess]
    [Area("Procurement")]
    public class PurchaseOrderController : BaseController
    {
        PortalService _portalService;
        HRISService _hrisService;
        BIMSService _bimsService;
        IConfiguration _configuration;
        IHostingEnvironment _environment;
        readonly string _baseHRISServerKey;

        public PurchaseOrderController(PortalService portalService, HRISService hRISService,BIMSService bIMSService,  IConfiguration configuration, IHostingEnvironment environment) 
        {
            _portalService = portalService;
            _configuration = configuration;
            _environment = environment;
            _hrisService = hRISService;
            _bimsService = bIMSService;
            _baseHRISServerKey = _configuration.GetValue<string>("BaseServer") + "HRISAPIEndpoint";
        }

        [Route("/PurchaseOrder")]
        [Route("/PurchaseOrder/PurchaseOrder")]
        public IActionResult PurchaseOrder()
        {
            return View();
        }

        [Route("/Procurement/GetPurchaseOrder")]
        public async Task<string> GetPurchaseOrder()
        {
            var dataTables = new List<PurchaseOrderHeaderModel>(); 
            var response = await _portalService.GetAsync(_configuration.GetValue<string>("WebPortalAPIEndpoint:GetPurchaseOrder"));

            List<PurchaseOrderHeaderModel> purchaseOrder = response.Data != null ? JsonConvert.DeserializeObject<List<PurchaseOrderHeaderModel>>(Convert.ToString(response.Data)) : null;

            foreach (var data in purchaseOrder)
            {
                dataTables.Add(new PurchaseOrderHeaderModel
                {
                    Id = data.Id,
                    PONumber = data.PONumber,
                    PODate = string.Format("{0:dd-MM-yyyy}", data.CreatedDate),
                    POStatus = data.POStatus,
                    StringGrandTotalAfterTax = string.Format("{0:N2}", data.GrandTotal)
                });
            }
            return JsonConvert.SerializeObject(dataTables);
        }

        [Route("/Procurement/PurchaseOrderDetail/{id}")]
        public async Task<IActionResult> PurchaseOrderDetail(int id)
        {
            PurchaseOrderHeaderModel model = new PurchaseOrderHeaderModel();
            List<PurchaseOrderVendorCategoryItemModel> vendorModel = new List<PurchaseOrderVendorCategoryItemModel>();
            List<PurchaseOrderItemModel> itemModel = new List<PurchaseOrderItemModel>();

            var response = await _portalService.GetAsync(_configuration.GetValue<string>("WebPortalAPIEndpoint:GetPurchaseOrderItemById") + "?id=" + id);

            if (response.Data != null)
            {
                model = response.Data != null ? JsonConvert.DeserializeObject<PurchaseOrderHeaderModel>(Convert.ToString(response.Data)) : null;

                decimal temptotal = model.ListItem
                 .Sum(item => item.TotalPrice);

                int tempppn = model.ListItem
                    .Select(x => x.PPN)
                    .FirstOrDefault();

                decimal ppnPrice = temptotal * tempppn / 100;
                model.GrandTotalAfterTax = model.GrandTotal + ppnPrice;

                model.StringGrandTotal= string.Format("{0:N2}", temptotal);
                model.Ppn = tempppn;
                model.stringPpn = string.Format("{0:N2}", ppnPrice);
                model.StringGrandTotalAfterTax = string.Format("{0:N2}", model.GrandTotalAfterTax);


                ViewData["List_Item"] = model.ListItem;


            }

            return View(model);
        }
    }
}

EmployeePortal/Areas/Procurement/Views/PurchaseOrder/PurchaseOrder.cshtml
@{
    ViewData["Title"] = "Purchase Order";
    Layout = "~/Views/Shared/_Layout.cshtml";
     var num = DateTime.Now.Ticks;
}

<!-- Start Page content -->
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div>
                    <h4 class="page-title-dashboard">List PO</h4>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
                        <li class="breadcrumb-item">PO</li>
                        <li class="breadcrumb-item active">List PO</li>
                    </ol>
                </div>
            </div>
        </div>
        <!-- end row -->

        <div class="row">
            <div class="col-12">
                <div class="card-box shadow-sm">
                    <table id="grid" class="table table-hover table-bordered" width="100%"></table>
                </div>
            </div>
        </div>
        <!-- end row -->
    </div> <!-- container -->
</div> <!-- content -->


@section Scripts {
    <script src="~/webportal/procurement/purchase-order.js?@num" type="text/javascript"></script>
}

EmployeePortal/Areas/Procurement/Views/PurchaseOrder/PurchaseOrderDetail.cshtml
@using Microsoft.AspNetCore.Http;
@using EmployeePortal.Areas.Procurement.Models.PurchaseOrder;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@model PurchaseOrderHeaderModel
@{
   
    List<PurchaseOrderItemModel> POItem = ViewData["List_Item"] != null ? (List<PurchaseOrderItemModel>)ViewData["List_Item"] : new List<PurchaseOrderItemModel>();

    int rowId = 1;
}

@{
    ViewData["Title"] = "PurchaseRequisitionStatusDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var num = DateTime.Now.Ticks;
}

<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div>
                    <h4 class="page-title-dashboard">@Model.PONumber</h4>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
                        <li class="breadcrumb-item">PO</li>
                        <li class="breadcrumb-item"><a href="@Url.Action("Status", "PurchaseOrder")">Status</a></li>
                        <li class="breadcrumb-item active">@ViewData["poNumber"]</li>
                    </ol>
                </div>
            </div>
        </div>
        <!-- end row -->

        @*<input asp-for="CompanyCode" type="hidden">
        <input asp-for="CompanyLocationCode" type="hidden">*@

        <div class="row">
            <div class="col-12">
                <div class="card-box shadow-sm">
                    <div class="form-group row">
                        <div class="col-12 col-sm-12 col-md-12 col-xl-12 pl-4 pr-4">
                            <div class="text-center col-12 mb-4">
                                <div class="h2-responsive">Purchase Order</div>
                            </div>
                            <div class="row mb-3">
                                <div class="row col-md-4 ml-2">
                                    <div class="font-weight-bold">
                                        FAP Group<br />
                                        @Model.CompanyName
                                    </div>
                                </div>
                                <div class="row col-md-4"></div>
                                <div class="row col-md-4">
                                    <label class="col-md-4 col-6">Departement</label>
                                    <div class="col-md-8 col-6">: @Model.DepartementName</div>
                                    <label class="col-md-4 col-6">Number</label>
                                    <div class="col-md-8 col-6">: @Model.PONumber</div>
                                    <label class="col-md-4 col-6">Date</label>
                                    <div class="col-md-8 col-6">: @Model.CreatedDate.ToString("dd-MM-yyyy")</div>
                                </div>
                            </div>

                            <h4 class="mt-3">Item/Service</h4>
                            <table id="table-detail-pr" class="table table-hover table-bordered" width="100%">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Item/Service Name</th>
                                        <th>Specification</th>
                                        <th>Purpose Description</th>
                                        <th>Quantity</th>
                                        <th>Currency</th>
                                        <th>Unit Price</th>
                                        <th>Total Price</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (PurchaseOrderItemModel item in POItem)
                                    {
                                        <tr>
                                            <td scope="row">@rowId</td>
                                            <td id="ItemName">
                                                @item.ItemName
                                            </td>
                                            <td id="Specification">
                                                <span>@item.Specification </span>
                                            </td>
                                            <td id="PurposeDesc">
                                                <span>@item.PurposeDesc </span>
                                            </td>
                                            <td id="col-qty" data-column="@item.Qty" align="right">
                                                @item.Qty
                                            </td>
                                            <td id="Currency">
                                                @item.Currency
                                            </td>
                                            <td id="UnitPrice" align="right">
                                                @item.UnitPriceString
                                            </td>
                                            <td id="col-totalPrice" data-column="@item.TotalPrice" align="right">
                                                @item.TotalPriceString
                                            </td>
                                        </tr>
                                        rowId++;
                                    }
                                </tbody>
                                <tfoot style="text-align:right; font-weight:bold">
                                    <tr>
                                        <th id="total" colspan="7">Total :</th>
                                        <td>@Model.StringGrandTotal</td>
                                    </tr>
                                    <tr>
                                        <th id="total" colspan="7">PPN <span>@Model.Ppn</span>% :</th>
                                        <td>@Model.stringPpn</td>
                                    </tr>
                                    <tr>
                                        <th id="total" colspan="7">Total After Tax :</th>
                                        <td>@Model.StringGrandTotalAfterTax</td>
                                    </tr>
                                </tfoot>
                            </table>

                        </div>
                    </div>
                </div>
                <div class="card-box shadow-sm" id="pr_wrap_budget" hidden>

                </div>
            </div>
        </div>

        <div class="hidden-print form-group account-btn text-center mt-3 mb-0">
            <div class="col-12">
                <div class="button-list">
                    <button class="btn w-lg btn-outline-custom waves-effect waves-light" aria-hidden="true" onclick=" window.open('/PurchaseOrder/PurchaseOrder','_self')"><i class="fa fa-reply mr-2"></i> Back</button>
                    <a href="javascript:window.print()" class="btn btn-custom waves-effect waves-light"><i class="fa fa-print mr-2"></i> Print</a>
                </div>
            </div>
        </div>
        <!-- end row -->
    </div> <!-- container -->
</div> <!-- content -->

@section Scripts {
    <script src="~/webportal/procurement/purchase-order-detail.js" type="text/javascript"></script>
}