EmployeePortal/Areas/Workflow/Controllers/ApprovalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EmployeePortal.Areas.Procurement.Models.Budget;
using EmployeePortal.Areas.Procurement.Models.PurchaseRequistion;
using EmployeePortal.Areas.Workflow.Models;
using EmployeePortal.Controllers;
using EmployeePortal.GlobalParam;
using EmployeePortal.Models.ResponseModel;
using EmployeePortal.Service;
using FirstResource.System.Library.EnumMaster;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;

namespace EmployeePortal.Areas.Workflow.Controllers
{
    [Area("Workflow")]
    [NoDirectAccess]
    public class ApprovalController : BaseController
    {
        readonly PortalService _portalService;
        readonly BIMSService _bimsService;
        readonly IConfiguration _configuration;
        public ApprovalController(PortalService portalService, BIMSService bimsService, IConfiguration configuration)
        {
            _portalService = portalService;
            _bimsService = bimsService;
            _configuration = configuration;
        }

        [Route("/Approval/Pending")]
        public async Task<IActionResult> Pending()
        {
            var response = await _portalService.GetAsync(_configuration.GetValue<string>("WebPortalAPIEndpoint:CountWorkflows") + "?userId=" + UserId + "&status=" + FirstResource.System.Library.EnumMaster.WorkflowProcessStatus.START.ToString());
            var totalPage = (response.Data + 5 - 1) / 5;

            ViewBag.TotalPage = totalPage;

            return View();
        }

        [Route("/Approval/PendingItem/{pageNumber}")]
        public async Task<PartialViewResult> _PendingItem(int pageNumber)
        {
            pageNumber = pageNumber - 1;

            var response = await _portalService.GetAsync(_configuration.GetValue<string>("WebPortalAPIEndpoint:GetWorkflows")
                + "?userId=" + UserId
                + "&pageNumber=" + pageNumber
                + "&processStatus=" + FirstResource.System.Library.EnumMaster.WorkflowProcessStatus.START.ToString());

            List<Models.WorkflowRequestModel> model = response.Data != null ? JsonConvert.DeserializeObject<List<Models.WorkflowRequestModel>>(Convert.ToString(response.Data)) : null;

            foreach (var single in model)
            {
                single.GrandTotalAfterTax = string.Format("{0:N2}", single.GrandTotal);
            }

            return PartialView(model);
        }

        [Route("/Approval/Approved")]
        public async Task<IActionResult> Approved()
        {
            var response = await _portalService.GetAsync(_configuration.GetValue<string>("WebPortalAPIEndpoint:CountWorkflows") + "?userId=" + UserId + "&status=" + FirstResource.System.Library.EnumMaster.WorkflowProcessStatus.END.ToString());
            var totalPage = (response.Data + 5 - 1) / 5;

            ViewBag.TotalPage = totalPage;

            return View();
        }

        [Route("/Approval/ApprovedItem/{pageNumber}")]
        public async Task<PartialViewResult> _ApprovedItem(int pageNumber)
        {
            pageNumber = pageNumber - 1;

            var response = await _portalService.GetAsync(_configuration.GetValue<string>("WebPortalAPIEndpoint:GetWorkflows")
                + "?userId=" + UserId
                + "&pageNumber=" + pageNumber
                + "&processStatus=" + FirstResource.System.Library.EnumMaster.WorkflowProcessStatus.END.ToString());
            List<Models.WorkflowRequestModel> model = response.Data != null ? JsonConvert.DeserializeObject<List<Models.WorkflowRequestModel>>(Convert.ToString(response.Data)) : null;

            foreach (var single in model)
            {
                single.GrandTotalAfterTax = string.Format("{0:N2}", single.GrandTotal);
            }

            return PartialView(model);
        }

        [Route("/Approval/Rejected")]
        public async Task<IActionResult> Rejected()
        {
            var response = await _portalService.GetAsync(_configuration.GetValue<string>("WebPortalAPIEndpoint:CountWorkflows") + "?userId=" + UserId + "&status=" + FirstResource.System.Library.EnumMaster.WorkflowProcessStatus.CANCEL.ToString());
            var totalPage = (response.Data + 5 - 1) / 5;

            ViewBag.TotalPage = totalPage;

            return View();
        }

        [Route("/Approval/RejectedItem/{pageNumber}")]
        public async Task<PartialViewResult> _RejectedItem(int pageNumber)
        {
            pageNumber = pageNumber - 1;

            var response = await _portalService.GetAsync(_configuration.GetValue<string>("WebPortalAPIEndpoint:GetWorkflows")
                + "?userId=" + UserId
                + "&pageNumber=" + pageNumber
                + "&processStatus=" + FirstResource.System.Library.EnumMaster.WorkflowProcessStatus.CANCEL.ToString());
            List<Models.WorkflowRequestModel> model = response.Data != null ? JsonConvert.DeserializeObject<List<Models.WorkflowRequestModel>>(Convert.ToString(response.Data)) : null;

            foreach (var single in model)
            {
                single.GrandTotalAfterTax = string.Format("{0:N2}", single.GrandTotal);
            }

            return PartialView(model);
        }

        [Route("/Approval/DetailItem/{workflowId}")]
        public async Task<PartialViewResult> _DetailItem(int workflowId, string workflowType)
        {
            var resWorkflowContext = await _portalService.GetAsync(_configuration.GetValue<string>("WebPortalAPIEndpoint:GetWorkflowById") + "?workflowId=" + workflowId);
            var resWorkflowHistoryApproval = await _portalService.GetAsync(_configuration.GetValue<string>("WebPortalAPIEndpoint:GetWorkflowHistoryById") + "?workflowId=" + workflowId);

            Models.WorkflowContextModel modelWorkflowContext = resWorkflowContext.Data != null ? JsonConvert.DeserializeObject<Models.WorkflowContextModel>(Convert.ToString(resWorkflowContext.Data)) : null;
            Models.WorkflowHistoryApprovalModel modelWorkflowHistoryApproval = resWorkflowHistoryApproval.Data != null ? JsonConvert.DeserializeObject<Models.WorkflowHistoryApprovalModel>(Convert.ToString(resWorkflowHistoryApproval.Data)) : null;
            var isWaitingApproval = modelWorkflowHistoryApproval.UserApproval.FirstOrDefault(n => n.UserActionId == Int32.Parse(UserId) && n.Activity.Activity == FirstResource.System.Library.Extensions.EnumExtensions.GetDescription(ActivityStatus.WAITING_APPROVAL).Result);

            var newFormatPRItem = modelWorkflowContext.WorkflowPurchaseRequsitionContext.ListItem.GroupBy(group => group.VendorName, (key, vendor) => new { VendorName = key, Items = vendor.ToList() });
            List<NewFormatPRItem> tempNewFormatPRItem = new List<NewFormatPRItem>();

            foreach (var single in newFormatPRItem)
            {
                tempNewFormatPRItem.Add(new NewFormatPRItem
                {
                    VendorName = single.VendorName,
                    Items = single.Items,
                    PPN = single.Items.Select(n => n.PPN).FirstOrDefault(),
                    PPNPrice = single.Items.Select(n => n.PPN).FirstOrDefault() * single.Items.Sum(n => n.TotalPrice) / 100,
                    TotalPrice = single.Items.Sum(n => n.TotalPrice),
                    GrandTotalAfterTax = single.Items.Sum(n => n.TotalPrice) + (single.Items.Select(n => n.PPN).FirstOrDefault() * single.Items.Sum(n => n.TotalPrice) / 100)
                });
            }

            modelWorkflowContext.NewFormatPRItem = tempNewFormatPRItem;

            ViewBag.WorkflowHistoryApproval = modelWorkflowHistoryApproval;
            ViewBag.MasterDataUserId = UserId;
            ViewBag.IsWaitingApproval = isWaitingApproval;

            return PartialView(modelWorkflowContext);
        }

        [HttpPost]
        [Route("/Approval/DetailBudget")]
        public async Task<PartialViewResult> _DetailBudget(ParamBudgetItem model)
        {
            var resBudget = await _bimsService.GetAsync(_configuration.GetValue<string>("FAPBIMSAPIEndpoint:GetItemBudget") + "?companyCode=" + model.CompanyCode + "&locationCode=" + model.LocationCode + "&budgetYear=" + model.Year + "&itemCode=" + model.BimsCode);
            var resItemRemaining = await _portalService.GetAsync(_configuration.GetValue<string>("WebPortalAPIEndpoint:GetRealizationBudgetItem") + "?bimsCode=" + model.BimsCode
                + "&year=" + model.Year);

            List<CreatePurchaseRequisitionItemModel> itemModel = resItemRemaining.Data != null ? JsonConvert.DeserializeObject<List<CreatePurchaseRequisitionItemModel>>(Convert.ToString(resItemRemaining.Data)) : null;
            BudgetModel budgetModel = resBudget.Data != null ? JsonConvert.DeserializeObject<BudgetModel>(Convert.ToString(resBudget.Data)) : null;

            if (budgetModel != null)
            {
                // Quantity
                budgetModel.QtyRealization = itemModel.Sum(t => Convert.ToDecimal(t.Qty));
                budgetModel.QtyRemaining = budgetModel.QtyBudget - budgetModel.QtyRealization;
                if (budgetModel.QtyRemaining < 0)
                {
                    budgetModel.QtyRemaining = 0;
                }
                budgetModel.QtyRequest = Convert.ToDecimal(model.Quantity);
                budgetModel.QtyRemainingTotal = budgetModel.QtyRemaining - budgetModel.QtyRequest;

                // Price
                budgetModel.TotalBudget = budgetModel.QtyBudget * budgetModel.ItemPrice;
                budgetModel.TotalBudgetRealization = Convert.ToDecimal(itemModel.Sum(t => t.TotalPrice));
                budgetModel.BudgetRemaining = budgetModel.TotalBudget - budgetModel.TotalBudgetRealization;
                if (budgetModel.BudgetRemaining < 0)
                {
                    budgetModel.BudgetRemaining = 0;
                }
                budgetModel.BudgetRequest =  Convert.ToDecimal(model.TotalPrice);

EmployeePortal/Views/Shared/Partial/_SideMenu.cshtml
@{
    var area = ViewContext.RouteData.Values["Area"];
    var controller = ViewContext.RouteData.Values["Controller"];
    var action = ViewContext.RouteData.Values["Action"];
}

    <ul class="metismenu" id="side-menu">
        <li>
            <a href="@Url.Action("Index", "Dashboard", new { area = "Dashboard" })" id="link-dashboard">
                <i class="fa fa-home"></i><span>Dashboard</span>
            </a>
        </li>
        <li class="menu-title">Purchasing</li>
        <li>
            <a href="javascript: void(0);"><i class="fa fa-shopping-cart"></i><span> PR </span> <span class="menu-arrow"></span></a>
            <ul class="nav-second-level" aria-expanded="false">
                <li><a href="@Url.Action("Index", "PurchaseRequisition", new { area = "Procurement" })">Create </a></li>
                <li><a href="@Url.Action("Status", "PurchaseRequisition", new { area = "Procurement" })">Status </a></li>
                <li>
                    <a href="javascript: void(0);"><span>Request Vendor</span> <span class="menu-arrow"></span></a>
                    <ul class="nav-third-level" aria-expanded="false">
                        <li><a href="@Url.Action("RFQ", "PurchaseRequisition", new { area = "Procurement" })">RFQ</a></li>
                        <li><a href="@Url.Action("QCF", "PurchaseRequisition", new { area = "Procurement" })">QCF</a></li>
                    </ul>
                </li>
            </ul>
        </li>
        <li>
            <a href="javascript: void(0);"><i class="fas fa-clipboard-list"></i><span> PO </span> <span class="menu-arrow"></span></a>
            <ul class="nav-second-level" aria-expanded="false">
                <li><a href="@Url.Action("PurchaseOrder", "PurchaseOrder", new { area = "Procurement" })">List PO</a></li>
            </ul>
        </li>
        <li>
            <a href="@Url.Action("Pending", "Approval", new { area = "Workflow" })" id="link-employee-approval">
                <i class="fa fa-check-square-o"></i><span>Approval</span>
            </a>
        </li>
        <li class="menu-title">Vendor</li>
        <li>
            <a href="javascript: void(0);"><i class="fa fa-id-card-o"></i><span> Vendor </span> <span class="menu-arrow"></span></a>
            <ul class="nav-second-level" aria-expanded="false">
                <li><a href="@Url.Action("Index", "Vendor", new { area = "Vendor" })" id="link-vendor-dashboard">Verify</a></li>
            </ul>
        </li>
    </ul>
<script>
    (function () {
        if ('@controller'.toLowerCase() == 'dashboard') {
            document.getElementById('link-dashboard').classList.add('active');
        } else if ('@controller'.toLowerCase() == 'vendor') {
            document.getElementById('link-vendor-dashboard').classList.add('active');
        } else if ('@controller'.toLowerCase() == 'personaldata') {
            document.getElementById('link-employee-personaldata').classList.add('active');
        } else if ('@controller'.toLowerCase() == 'leavepermission') {
            document.getElementById('link-employee-attendance').classList.add('active');
            document.getElementById('link-employee-attendance').children[0].classList.add('active');
            document.getElementById('link-employee-attendance-leave').classList.add('active');
        } else if ('@controller'.toLowerCase() == 'approval') {
            document.getElementById('link-employee-approval').classList.add('active');
        }
    })();
</script>

EmployeePortal/Views/Shared/Partial/_TopBar.cshtml
@using Microsoft.AspNetCore.Http;

<div class="topbar">
    <nav class="navbar-custom">
        <!-- LOGO -->
        <div class="logo-box">
            <a href="#" class="logo">
                <img src="~/lib/fap-van/assets/images/e-pis.png" alt="" height="40">
            </a>
        </div>
        <ul class="list-unstyled topbar-right-menu float-right mb-0">
            <li class="dropdown notification-list">
                <a class="nav-link dropdown-toggle arrow-none" data-toggle="dropdown" href="#" role="button"
                   aria-haspopup="false" aria-expanded="false">
                    <i class="fi-bell noti-icon"></i>
                    <span class="badge badge-notification badge-pill noti-icon-badge">4</span>
                </a>
                <div class="dropdown-menu dropdown-menu-right dropdown-menu-animated dropdown-lg">
                    <!-- item-->
                    <div class="dropdown-item noti-title">
                        <h5 class="m-0"><span class="float-right"><a href="" class="text-dark"><small>Clear All</small></a> </span>Notification</h5>
                    </div>
                    <div class="slimscroll" style="max-height: 230px;">
                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <div class="notify-icon bg-success"><i class="mdi mdi-comment-account-outline"></i></div>
                            <p class="notify-details">Complete your Data Vendor<small class="text-muted">1 min ago</small></p>
                        </a>
                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <div class="notify-icon bg-info"><i class="mdi mdi-account-plus"></i></div>
                            <p class="notify-details">Your data is incomplete<small class="text-muted">5 hours ago</small></p>
                        </a>
                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <div class="notify-icon bg-danger"><i class="mdi mdi-heart"></i></div>
                            <p class="notify-details">New Order<small class="text-muted">3 days ago</small></p>
                        </a>
                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <div class="notify-icon bg-success"><i class="mdi mdi-comment-account-outline"></i></div>
                            <p class="notify-details">Complete your Data Vendor<small class="text-muted">1 min ago</small></p>
                        </a>
                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <div class="notify-icon bg-info"><i class="mdi mdi-account-plus"></i></div>
                            <p class="notify-details">Your data is incomplete<small class="text-muted">5 hours ago</small></p>
                        </a>
                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <div class="notify-icon bg-danger"><i class="mdi mdi-heart"></i></div>
                            <p class="notify-details">New Order<small class="text-muted">3 days ago</small></p>
                        </a>
                    </div>
                    <!-- All-->
                    <a href="javascript:void(0);" class="dropdown-item text-center text-primary notify-item notify-all">
                        View all <i class="fi-arrow-right"></i>
                    </a>
                </div>
            </li>
            <li class="dropdown notification-list">
                <a class="nav-link dropdown-toggle nav-user" data-toggle="dropdown" href="#" role="button"
                   aria-haspopup="false" aria-expanded="false">
                    <img src="@Url.Content("~/images/avatar-2.jpg")" alt="user" class="rounded-circle">
                    <span class="ml-1">@Context.Session.GetString("_UserName")<i class="mdi mdi-chevron-down"></i> </span>
                </a>
                <div class="dropdown-menu dropdown-menu-right dropdown-menu-animated profile-dropdown">
                    <!-- item-->
                    <a href="@Url.Action("Logout", "Account", new { area = "Account" })" class="dropdown-item notify-item">
                        <i class="fi-power"></i> <span>Logout</span>
                    </a>
                </div>
            </li>
        </ul>
        <ul class="list-inline menu-left mb-0">
            <li class="float-left">
                <button class="button-menu-mobile open-left">
                    <i class="dripicons-menu"></i>
                </button>
            </li>
        </ul>
    </nav>
</div>